---
- hosts: localhost
  tasks:
    - assert:
        that:
          - ansible_env.AWS_ACCESS_KEY is defined
          - ansible_env.AWS_SECRET_KEY is defined

- hosts: localhost
  roles:
     - { role: aws_bootstrap_consul,
         ssh_user: ubuntu,
         ec2_region: us-east-1,
         key_name: "{{ key_name }}",
         instance_type: t2.small,
         instance_count: 3,
         vpc_id: vpc-34b02450,
         vpc_subnet_id: subnet-7b5f4b50,
         ebs_vol_size: 1000,
         root_device_path: /dev/sda1,
         ec2_image: ami-d05e75b8,
         security_group: [test-sg]
         }
