---
- hosts: localhost
  tasks:
    - assert:
        that:
          - ansible_env.AWS_ACCESS_KEY is defined
          - ansible_env.AWS_SECRET_KEY is defined

- name: deploy consul client
  hosts: "{{ host_type }}"
  sudo: True
  gather_facts: true
  vars:
    consul_datacenter: "{{ datacenter }}"
  roles:
    - consul-services
